import * as Print from "expo-print";
import * as Sharing from "expo-sharing";
import { Platform, Alert } from "react-native";

const escape = (s: string | number | null | undefined): string => {
  if (s === null || s === undefined) return "";
  return String(s)
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
};

const baseStyles = `
<style>
  body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif; color: #0F172A; padding: 32px; }
  h1 { font-size: 22px; margin: 0 0 6px; color: #1E40AF; }
  .sub { color: #64748B; font-size: 13px; margin-bottom: 24px; }
  .meta { display: flex; justify-content: space-between; margin-bottom: 16px; font-size: 12px; color: #64748B; }
  table { width: 100%; border-collapse: collapse; margin-bottom: 16px; }
  th, td { text-align: left; padding: 10px 12px; border-bottom: 1px solid #E2E8F0; font-size: 13px; vertical-align: top; }
  th { background: #F1F5F9; color: #475569; font-weight: 600; text-transform: uppercase; font-size: 11px; letter-spacing: 0.5px; }
  td.num, th.num { text-align: right; font-variant-numeric: tabular-nums; white-space: nowrap; }
  .credit { color: #16A34A; }
  .debit { color: #DC2626; }
  .note { color: #64748B; font-size: 11px; margin-top: 3px; font-style: italic; }
  .multi-head td { background: #F8FAFC; font-weight: 700; color: #1E293B; border-bottom: 2px solid #E2E8F0; padding-top: 12px; }
  .multi-item td { padding-top: 6px; padding-bottom: 6px; }
  .multi-item td:first-child { padding-left: 28px; color: #334155; }
  .multi-subtotal td { background: #FAFAFA; font-weight: 700; border-top: 1px solid #CBD5E1; }
  .multi-subtotal td:first-child { text-align: right; color: #475569; font-style: italic; padding-right: 12px; }
  .totals { margin-top: 24px; border-top: 2px solid #1E40AF; padding-top: 12px; }
  .totals .row { display: flex; justify-content: space-between; padding: 6px 0; font-size: 14px; }
  .totals .net { font-weight: 700; font-size: 18px; color: #1E40AF; margin-top: 6px; padding-top: 10px; border-top: 1px solid #E2E8F0; }
  .badge { display: inline-block; padding: 2px 8px; border-radius: 4px; font-size: 11px; font-weight: 600; }
  .badge.done { background: #DCFCE7; color: #16A34A; }
  .badge.pending { background: #FEF3C7; color: #B45309; }
  .footer { margin-top: 32px; font-size: 11px; color: #94A3B8; text-align: center; border-top: 1px solid #E2E8F0; padding-top: 12px; }
</style>
`;

const formatDate = (d: string): string => {
  try {
    return new Date(d).toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" });
  } catch { return d; }
};

const formatDT = (d?: string | null): string => {
  if (!d) return "—";
  try { return new Date(d).toLocaleString(); } catch { return d; }
};

const money = (n: number): string =>
  `$${(n ?? 0).toLocaleString("en-US", { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`;

export type ChecklistReportData = {
  title: string;       // "Opening Checklist" / "Closing Checklist"
  storeName: string;
  date: string;        // YYYY-MM-DD
  tasks: { id: string; title: string }[];
  completedIds: string[];
  submitted: boolean;
  submittedBy?: string | null;
  submittedAt?: string | null;
};

export const buildChecklistHtml = (d: ChecklistReportData): string => {
  const rows = d.tasks
    .map((t) => {
      const done = d.completedIds.includes(t.id);
      return `<tr>
        <td>${escape(t.title)}</td>
        <td class="num"><span class="badge ${done ? "done" : "pending"}">${done ? "Completed" : "Pending"}</span></td>
      </tr>`;
    })
    .join("");
  const completed = d.tasks.filter((t) => d.completedIds.includes(t.id)).length;
  return `<!DOCTYPE html><html><head><meta charset="utf-8" />${baseStyles}</head>
  <body>
    <h1>${escape(d.title)}</h1>
    <div class="sub">${escape(d.storeName)} • ${formatDate(d.date)}</div>
    <div class="meta">
      <div>${completed}/${d.tasks.length} completed</div>
      <div>Status: <strong>${d.submitted ? "Submitted" : "Open"}</strong></div>
    </div>
    <table>
      <thead><tr><th>Task</th><th class="num">Status</th></tr></thead>
      <tbody>${rows || `<tr><td colspan="2" style="color:#94A3B8;">No tasks configured</td></tr>`}</tbody>
    </table>
    ${d.submitted ? `<div class="meta"><div>Submitted by ${escape(d.submittedBy)}</div><div>${escape(formatDT(d.submittedAt))}</div></div>` : ""}
    <div class="footer">Generated by Grocery Ops · ${escape(new Date().toLocaleString())}</div>
  </body></html>`;
};

export type ShoppingReportItem = {
  name: string;
  quantity: number;
  note?: string;
  supplier: string;
  purchase_price_type: "regular" | "deal";
  purchase_price?: number | null;
};

export const buildShoppingHtml = (d: { storeName: string; listName: string; supplierLabel: string; items: ShoppingReportItem[] }): string => {
  const rows = d.items.length
    ? d.items.map((it) => {
        const line = (it.purchase_price != null && it.quantity) ? (it.purchase_price * it.quantity) : null;
        return `<tr>
          <td>${escape(it.name)}${it.note ? `<div class="note">${escape(it.note)}</div>` : ""}</td>
          <td class="num">${it.quantity}</td>
          <td>${escape(it.supplier)}</td>
          <td>${it.purchase_price_type === "deal" ? "Deal" : "Regular"}</td>
          <td class="num">${it.purchase_price != null ? money(it.purchase_price) : "—"}</td>
          <td class="num">${line != null ? money(line) : "—"}</td>
        </tr>`;
      }).join("")
    : `<tr><td colspan="6" style="color:#94A3B8;">No items</td></tr>`;
  const grand = d.items.reduce((s, it) => s + ((it.purchase_price || 0) * (it.quantity || 0)), 0);
  return `<!doctype html><html><head><meta charset="utf-8" />${baseStyles}</head>
  <body>
    <h1>Shopping List — ${escape(d.listName)}</h1>
    <div class="sub">${escape(d.storeName)} · Supplier filter: <b>${escape(d.supplierLabel)}</b> · ${new Date().toLocaleString()}</div>
    <table>
      <thead><tr><th>Item</th><th class="num">Qty</th><th>Supplier</th><th>Type</th><th class="num">Price</th><th class="num">Line total</th></tr></thead>
      <tbody>${rows}</tbody>
    </table>
    <div class="totals"><div class="net"><span>Estimated total</span><span>${money(grand)}</span></div></div>
    <div class="footer">Generated by Store Ops</div>
  </body></html>`;
};

export type AccountingReportData = {
  storeName: string;
  date: string;
  heads: {
    id: string;
    name: string;
    type: "credit" | "debit";
    is_cash?: boolean;
    allow_notes?: boolean;
    multiple_entries?: boolean;
  }[];
  entries: Record<string, any>; // number | {amount,note} | [{label,note,amount}]
  openingBalance: number | null;   // null = hidden (employee)
  closingBalance: number | null;
  totalCredit: number;
  totalDebit: number;
  net: number;
  submitted: boolean;
  submittedBy?: string | null;
  submittedAt?: string | null;
  showBalances: boolean;
};

const entryAmount = (v: any): number => {
  if (v === null || v === undefined) return 0;
  if (typeof v === "number") return v;
  if (typeof v === "string") return parseFloat(v) || 0;
  if (Array.isArray(v)) return v.reduce((s, it) => s + (Number(it?.amount) || 0), 0);
  if (typeof v === "object") return Number(v.amount) || 0;
  return 0;
};

export const buildAccountingHtml = (d: AccountingReportData): string => {
  const credits = d.heads.filter((h) => h.type === "credit");
  const debits = d.heads.filter((h) => h.type === "debit");

  const rowFor = (h: { id: string; name: string; type: string; allow_notes?: boolean; multiple_entries?: boolean }): string => {
    const val = d.entries[h.id];
    const total = entryAmount(val);
    // Multi-entry head: list each item with a banner row + indented items + subtotal
    if (h.multiple_entries && Array.isArray(val) && val.length > 0) {
      const itemsHtml = val
        .map((it: any) => {
          const label = escape(it.label || "—");
          const note = it.note ? `<div class="note">${escape(it.note)}</div>` : "";
          const amt = Number(it.amount) || 0;
          return `<tr class="multi-item"><td>• ${label}${note}</td><td class="num ${h.type}">${money(amt)}</td></tr>`;
        })
        .join("");
      return `<tr class="multi-head"><td>${escape(h.name)} <span style="font-weight:400;color:#64748B;font-size:11px;">(${val.length} ${val.length === 1 ? "entry" : "entries"})</span></td><td class="num ${h.type}" style="font-weight:700;">${money(total)}</td></tr>${itemsHtml}<tr class="multi-subtotal"><td>Subtotal</td><td class="num ${h.type}">${money(total)}</td></tr>`;
    }
    // Multi-entry head but no items yet
    if (h.multiple_entries) {
      return `<tr><td>${escape(h.name)} <span style="color:#94A3B8;font-size:11px;">(no entries)</span></td><td class="num ${h.type}">${money(0)}</td></tr>`;
    }
    // Single with note
    if (h.allow_notes && val && typeof val === "object" && !Array.isArray(val)) {
      const note = (val as any).note ? `<div class="note">${escape((val as any).note)}</div>` : "";
      return `<tr><td>${escape(h.name)}${note}</td><td class="num ${h.type}">${money(total)}</td></tr>`;
    }
    return `<tr><td>${escape(h.name)}</td><td class="num ${h.type}">${money(total)}</td></tr>`;
  };

  const creditRows = credits.length ? credits.map(rowFor).join("") : `<tr><td colspan="2" style="color:#94A3B8;">No credit heads</td></tr>`;
  const debitRows = debits.length ? debits.map(rowFor).join("") : `<tr><td colspan="2" style="color:#94A3B8;">No debit heads</td></tr>`;

  return `<!DOCTYPE html><html><head><meta charset="utf-8" />${baseStyles}</head>
  <body>
    <h1>Cash Accounting Report</h1>
    <div class="sub">${escape(d.storeName)} • ${formatDate(d.date)}</div>

    <h3 style="color:#16A34A;margin-top:18px;">Credits</h3>
    <table><thead><tr><th>Head</th><th class="num">Amount</th></tr></thead><tbody>${creditRows}</tbody></table>

    <h3 style="color:#DC2626;margin-top:18px;">Debits</h3>
    <table><thead><tr><th>Head</th><th class="num">Amount</th></tr></thead><tbody>${debitRows}</tbody></table>

    <div class="totals">
      ${d.showBalances && d.openingBalance !== null ? `<div class="row"><div>Opening Balance</div><div>${money(d.openingBalance)}</div></div>` : ""}
      <div class="row"><div>Total Credit</div><div class="credit">${money(d.totalCredit)}</div></div>
      <div class="row"><div>Total Debit</div><div class="debit">${money(d.totalDebit)}</div></div>
      <div class="row net"><div>Net (Credit − Debit)</div><div>${money(d.net)}</div></div>
      ${d.showBalances && d.closingBalance !== null ? `<div class="row" style="margin-top:8px;font-weight:600;"><div>Closing Balance</div><div>${money(d.closingBalance)}</div></div>` : ""}
    </div>
    ${d.submitted ? `<div class="meta" style="margin-top:24px;"><div>Submitted by ${escape(d.submittedBy)}</div><div>${escape(formatDT(d.submittedAt))}</div></div>` : ""}
    <div class="footer">Generated by Grocery Ops · ${escape(new Date().toLocaleString())}</div>
  </body></html>`;
};

export async function generateAndShare(html: string, filename: string): Promise<void> {
  try {
    if (Platform.OS === "web") {
      // Open print preview in a new window (web fallback)
      const w = window.open("", "_blank");
      if (!w) {
        Alert.alert("Popup blocked", "Allow popups to download the PDF.");
        return;
      }
      w.document.write(html);
      w.document.close();
      setTimeout(() => w.print(), 300);
      return;
    }
    const { uri } = await Print.printToFileAsync({ html });
    const canShare = await Sharing.isAvailableAsync();
    if (canShare) {
      await Sharing.shareAsync(uri, { mimeType: "application/pdf", dialogTitle: filename, UTI: ".pdf" });
    } else {
      Alert.alert("PDF generated", `Saved at: ${uri}`);
    }
  } catch (e: any) {
    Alert.alert("PDF error", e?.message || String(e));
  }
}
