import * as Print from "expo-print";
import * as Sharing from "expo-sharing";
import { Platform, Alert } from "react-native";

const escape = (s: string | number | null | undefined): string => {
  if (s === null || s === undefined) return "";
  return String(s)
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
};

const baseStyles = `
<style>
  body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif; color: #0F172A; padding: 32px; }
  h1 { font-size: 22px; margin: 0 0 6px; color: #1E40AF; }
  .sub { color: #64748B; font-size: 13px; margin-bottom: 24px; }
  .meta { display: flex; justify-content: space-between; margin-bottom: 16px; font-size: 12px; color: #64748B; }
  table { width: 100%; border-collapse: collapse; margin-bottom: 16px; }
  th, td { text-align: left; padding: 10px 12px; border-bottom: 1px solid #E2E8F0; font-size: 13px; }
  th { background: #F1F5F9; color: #475569; font-weight: 600; text-transform: uppercase; font-size: 11px; letter-spacing: 0.5px; }
  td.num, th.num { text-align: right; font-variant-numeric: tabular-nums; }
  .credit { color: #16A34A; }
  .debit { color: #DC2626; }
  .totals { margin-top: 24px; border-top: 2px solid #1E40AF; padding-top: 12px; }
  .totals .row { display: flex; justify-content: space-between; padding: 6px 0; font-size: 14px; }
  .totals .net { font-weight: 700; font-size: 18px; color: #1E40AF; margin-top: 6px; padding-top: 10px; border-top: 1px solid #E2E8F0; }
  .badge { display: inline-block; padding: 2px 8px; border-radius: 4px; font-size: 11px; font-weight: 600; }
  .badge.done { background: #DCFCE7; color: #16A34A; }
  .badge.pending { background: #FEF3C7; color: #B45309; }
  .footer { margin-top: 32px; font-size: 11px; color: #94A3B8; text-align: center; border-top: 1px solid #E2E8F0; padding-top: 12px; }
</style>
`;

const formatDate = (d: string): string => {
  try {
    return new Date(d).toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" });
  } catch { return d; }
};

const formatDT = (d?: string | null): string => {
  if (!d) return "—";
  try { return new Date(d).toLocaleString(); } catch { return d; }
};

const money = (n: number): string =>
  `$${(n ?? 0).toLocaleString("en-US", { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`;

export type ChecklistReportData = {
  title: string;       // "Opening Checklist" / "Closing Checklist"
  storeName: string;
  date: string;        // YYYY-MM-DD
  tasks: { id: string; title: string }[];
  completedIds: string[];
  submitted: boolean;
  submittedBy?: string | null;
  submittedAt?: string | null;
};

export const buildChecklistHtml = (d: ChecklistReportData): string => {
  const rows = d.tasks
    .map((t) => {
      const done = d.completedIds.includes(t.id);
      return `<tr>
        <td>${escape(t.title)}</td>
        <td class="num"><span class="badge ${done ? "done" : "pending"}">${done ? "Completed" : "Pending"}</span></td>
      </tr>`;
    })
    .join("");
  const completed = d.tasks.filter((t) => d.completedIds.includes(t.id)).length;
  return `<!DOCTYPE html><html><head><meta charset="utf-8" />${baseStyles}</head>
  <body>
    <h1>${escape(d.title)}</h1>
    <div class="sub">${escape(d.storeName)} • ${formatDate(d.date)}</div>
    <div class="meta">
      <div>${completed}/${d.tasks.length} completed</div>
      <div>Status: <strong>${d.submitted ? "Submitted" : "Open"}</strong></div>
    </div>
    <table>
      <thead><tr><th>Task</th><th class="num">Status</th></tr></thead>
      <tbody>${rows || `<tr><td colspan="2" style="color:#94A3B8;">No tasks configured</td></tr>`}</tbody>
    </table>
    ${d.submitted ? `<div class="meta"><div>Submitted by ${escape(d.submittedBy)}</div><div>${escape(formatDT(d.submittedAt))}</div></div>` : ""}
    <div class="footer">Generated by Grocery Ops · ${escape(new Date().toLocaleString())}</div>
  </body></html>`;
};

export type AccountingReportData = {
  storeName: string;
  date: string;
  heads: { id: string; name: string; type: "credit" | "debit"; is_cash?: boolean }[];
  entries: Record<string, number>; // may be empty for employee
  openingBalance: number | null;   // null = hidden (employee)
  closingBalance: number | null;
  totalCredit: number;
  totalDebit: number;
  net: number;
  submitted: boolean;
  submittedBy?: string | null;
  submittedAt?: string | null;
  showBalances: boolean;
};

export const buildAccountingHtml = (d: AccountingReportData): string => {
  const credits = d.heads.filter((h) => h.type === "credit");
  const debits = d.heads.filter((h) => h.type === "debit");

  const rowFor = (h: { id: string; name: string; type: string }): string => {
    const amt = d.entries[h.id] ?? 0;
    return `<tr><td>${escape(h.name)}</td><td class="num ${h.type}">${money(amt)}</td></tr>`;
  };

  const creditRows = credits.length ? credits.map(rowFor).join("") : `<tr><td colspan="2" style="color:#94A3B8;">No credit heads</td></tr>`;
  const debitRows = debits.length ? debits.map(rowFor).join("") : `<tr><td colspan="2" style="color:#94A3B8;">No debit heads</td></tr>`;

  return `<!DOCTYPE html><html><head><meta charset="utf-8" />${baseStyles}</head>
  <body>
    <h1>Accounting Report</h1>
    <div class="sub">${escape(d.storeName)} • ${formatDate(d.date)}</div>

    <h3 style="color:#16A34A;margin-top:18px;">Credits</h3>
    <table><thead><tr><th>Head</th><th class="num">Amount</th></tr></thead><tbody>${creditRows}</tbody></table>

    <h3 style="color:#DC2626;margin-top:18px;">Debits</h3>
    <table><thead><tr><th>Head</th><th class="num">Amount</th></tr></thead><tbody>${debitRows}</tbody></table>

    <div class="totals">
      ${d.showBalances && d.openingBalance !== null ? `<div class="row"><div>Opening Balance</div><div>${money(d.openingBalance)}</div></div>` : ""}
      <div class="row"><div>Total Credit</div><div class="credit">${money(d.totalCredit)}</div></div>
      <div class="row"><div>Total Debit</div><div class="debit">${money(d.totalDebit)}</div></div>
      <div class="row net"><div>Net (Credit − Debit)</div><div>${money(d.net)}</div></div>
      ${d.showBalances && d.closingBalance !== null ? `<div class="row" style="margin-top:8px;font-weight:600;"><div>Closing Balance</div><div>${money(d.closingBalance)}</div></div>` : ""}
    </div>
    ${d.submitted ? `<div class="meta" style="margin-top:24px;"><div>Submitted by ${escape(d.submittedBy)}</div><div>${escape(formatDT(d.submittedAt))}</div></div>` : ""}
    <div class="footer">Generated by Grocery Ops · ${escape(new Date().toLocaleString())}</div>
  </body></html>`;
};

export async function generateAndShare(html: string, filename: string): Promise<void> {
  try {
    if (Platform.OS === "web") {
      // Open print preview in a new window (web fallback)
      const w = window.open("", "_blank");
      if (!w) {
        Alert.alert("Popup blocked", "Allow popups to download the PDF.");
        return;
      }
      w.document.write(html);
      w.document.close();
      setTimeout(() => w.print(), 300);
      return;
    }
    const { uri } = await Print.printToFileAsync({ html });
    const canShare = await Sharing.isAvailableAsync();
    if (canShare) {
      await Sharing.shareAsync(uri, { mimeType: "application/pdf", dialogTitle: filename, UTI: ".pdf" });
    } else {
      Alert.alert("PDF generated", `Saved at: ${uri}`);
    }
  } catch (e: any) {
    Alert.alert("PDF error", e?.message || String(e));
  }
}
